### PR TITLE
fix uninitialized constant in lib/valid_email/validate_email.rb

### PR DESCRIPTION
**Pull request by tmornini**
This file needed a ```require 'mail'``` to eliminate the exception.

### CODE REVIEW

**Comment by tmornini** [comment]
@hallelujah Ping :-)

**Comment by merhard** [comment]
+1

@tmornini, I would also remove `require 'mail'`in the following places:
- [ban_disposable_email_validator.rb](https://github.com/hallelujah/valid_email/blob/master/lib/valid_email/ban_disposable_email_validator.rb#L3)
- [email_validator.rb](https://github.com/hallelujah/valid_email/blob/master/lib/valid_email/email_validator.rb#L3)
- [mx_validator.rb](https://github.com/hallelujah/valid_email/blob/master/lib/valid_email/mx_validator.rb#L3)

Adding `require 'mail'` to [validate_email.rb](https://github.com/hallelujah/valid_email/blob/master/lib/valid_email/validate_email.rb) makes these lines unnecessary.

**Comment by tmornini** [comment]
@merhard Are you sure the specs will run OK?

I'm a big fan of every file requiring everything it needs. Would have solved this issue, right? :-)

**Comment by merhard** [comment]
@tmornini 100% (I cloned your fork, made those changes, and ran the specs myself to confirm). If you look at the code in those files, they do not use anything from the Mail gem. `require 'mail'` is only there to make ValidateEmail work, which your pull request has fixed.

**Comment by tmornini** [comment]
@merhard Thanks! Forgive my ignorance, but can you join into this PR with an additional commit? If so, please do so!

**Comment by tmornini** [comment]
@hallelujah :+1:

**Comment by tmornini** [comment]
Ping...

**Comment by tmornini** [comment]
@hallelujah Ping!

**Comment by tmornini** [comment]
@hallelujah PIng...

**Pull request merged**
